In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Binarizer

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.drop(columns=['PassengerId', 'Survived', 'Pclass' ,'Name' ,'Sex', 'SibSp', 'Parch', 'Parch', 'Fare', 'Cabin', 'Embarked', 'Ticket'], inplace=True)

In [8]:
df

      Age
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
..    ...
886  27.0
887  19.0
888   NaN
889  26.0
890  32.0

[891 rows x 1 columns]

In [11]:
df.dropna(inplace=True)

In [12]:
b = Binarizer(threshold=18, copy=True)

In [14]:
df['transformed'] = b.fit_transform(df)

In [19]:
df.sample(5)

      Age  transformed
406  51.0          1.0
417  18.0          0.0
774  54.0          1.0
344  36.0          1.0
767  30.5          1.0