In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.drop(columns=['PassengerId', 'Survived', 'Name', 'Sex', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Pclass', 'Embarked'], inplace=True)

In [6]:
df

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [7]:
df.dropna(inplace=True)

In [8]:
df.isnull().sum()

Age     0
Fare    0
dtype: int64

In [9]:
df.head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

### lets play it simple without train test split
### We are just practicing binning.

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import KBinsDiscretizer

In [11]:
kbd = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')

In [12]:
ct = ColumnTransformer([
    ('kbd_age', kbd, ['Age']),
    ('kbd_fare', kbd, ['Fare'])
],
                      remainder='passthrough')

In [13]:
transformed = ct.fit_transform(df)

In [14]:
transformed

array([[2., 0.],
       [4., 1.],
       [3., 0.],
       ...,
       [2., 0.],
       [3., 0.],
       [3., 0.]], shape=(714, 2))

In [15]:
ct.named_transformers_['kbd_age'].bin_edges_, ct.named_transformers_['kbd_fare'].bin_edges_

(array([array([ 0.42 ,  8.378, 16.336, 24.294, 32.252, 40.21 , 48.168, 56.126,
               64.084, 72.042, 80.   ])                                       ],
       dtype=object),
 array([array([  0.     ,  51.23292, 102.46584, 153.69876, 204.93168, 256.1646 ,
               307.39752, 358.63044, 409.86336, 461.09628, 512.3292 ])          ],
       dtype=object))

In [18]:
pd.DataFrame(transformed, columns=df.columns, dtype=int).head()

   Age  Fare
0    2     0
1    4     1
2    3     0
3    4     1
4    4     0

In [19]:
df.head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500