# Mentos Zindagi

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('covid_toy.csv')

In [6]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:5],
                                                   df.iloc[:,-1:],
                                                   test_size=0.3,
                                                   random_state = 2)

In [10]:
X_train

    age  gender  fever   cough       city
65   69  Female  102.0    Mild  Bangalore
1    27    Male  100.0    Mild      Delhi
18   64  Female   98.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
36   38  Female  101.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
43   22  Female   99.0    Mild  Bangalore
22   71  Female   98.0  Strong    Kolkata
72   83  Female  101.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi

[70 rows x 5 columns]

In [11]:
from sklearn.compose import ColumnTransformer

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [15]:
transformer = ColumnTransformer(transformers=[
    ('t1', SimpleImputer(), ['fever']),
    ('t2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('t3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
],
                                remainder='passthrough'
                               )

In [17]:
transformer.fit_transform(X_train).shape

(70, 7)